use std::ptr;

use crate::constants::PACKET_HEADER_SIZE;

use super::{PacketHeader, endian::FixEndianness, macros::define_packets, packet_id::PacketId, packets};

define_packets! {
    Motion      => packets::motion::PacketMotion,
    CarDamage   => packets::car_damage::PacketCarDamage,
    CarMotionEx => packets::motion_ex::PacketMotionEx,
    TimeTrial   => packets::time_trial::PacketTimeTrial,
    TyreSets    => packets::tyre_sets::PacketTyreSets,
    CarSetups   => packets::car_setups::PacketCarSetups,
    LapData      => packets::lap_data::PacketLapData,
    LapPositions   => packets::lap_positions::PacketLapPositions,
    SessionHistory => packets::session_history::PacketSessionHistory,
    CarTelemetry   => packets::car_telemetry::PacketCarTelemetry,
    LobbyInfo      => packets::lobby_info::PacketLobbyInfo,
    Participants          => packets::participants::PacketParticipants,
    FinalClassification   => packets::final_classification::PacketFinalClassification,
    CarStatus             => packets::car_status::PacketCarStatus,
    Session               => packets::session::PacketSession,
    Event                 => packets::event::PacketEvent,
}

#[derive(Debug)]
pub enum ParseError {
    /// The buffer was too short to contain the required number of bytes.
    BufferTooShort { needed: usize, got: usize },
    /// The `packet_id` byte did not match any known value.
    UnknownPacketId(u8),
    /// The packet id is known but no wire struct has been implemented yet.
    Unsupported(PacketId),
}

impl std::fmt::Display for ParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::BufferTooShort { needed, got } => {
                write!(f, "buffer too short: needed {needed} bytes, got {got}")
            }
            Self::UnknownPacketId(id) => write!(f, "unknown packet id: {id}"),
            Self::Unsupported(id) => write!(f, "packet {id:?} is not yet implemented in v2"),
        }
    }
}

impl std::error::Error for ParseError {}

/// Parse a raw UDP buffer into a typed [`V2Packet`].
///
/// 1. Reads the 29-byte [`PacketHeader`] via `ptr::read_unaligned`.
/// 2. Converts `packet_id` to the [`PacketId`] enum.
/// 3. Dispatches to the appropriate packet type (generated by [`define_packets!`]).
pub fn parse(buf: &[u8]) -> Result<V2Packet, ParseError> {
    if buf.len() < PACKET_HEADER_SIZE {
        return Err(ParseError::BufferTooShort {
            needed: PACKET_HEADER_SIZE,
            got: buf.len(),
        });
    }

    // SAFETY: buf is at least PACKET_HEADER_SIZE bytes and PacketHeader is
    // repr(C, packed) with only primitive fields, so any bit pattern is valid.
    let header = unsafe { ptr::read_unaligned(buf.as_ptr() as *const PacketHeader) }.fix_endianness();

    let packet_id = header.packet_id().map_err(ParseError::UnknownPacketId)?;

    dispatch(packet_id, buf)
}

/// Cast the front of `buf` to `T` via `ptr::read_unaligned`.
///
/// # Safety
/// `T` must be `repr(C, packed)` with only primitive fields (no padding, any
/// bit pattern valid). All packet structs in this module satisfy this.
fn read_packet<T: Copy + FixEndianness>(buf: &[u8]) -> Result<T, ParseError> {
    let needed = std::mem::size_of::<T>();
    if buf.len() < needed {
        return Err(ParseError::BufferTooShort { needed, got: buf.len() });
    }
    // SAFETY: see above.
    Ok(unsafe { ptr::read_unaligned(buf.as_ptr() as *const T) }.fix_endianness())
}
